version: '3' 
services: 
  jira:
    container_name: jira_local
    image: atlassian/jira-software:latest 
    environment:
     - ATL_PROXY_NAME=jira.internal
     - ATL_PROXY_PORT=80
     - ATL_TOMCAT_SCHEME=http 
    volumes: 
      - jiraVolume

  confluence: 
    container_name: confluence_local
    image: atlassian/confluence-server:latest
    environment: 
     - ATL_PROXY_NAME=confluence.internal
     - ATL_PROXY_PORT=80
     - ATL_TOMCAT_SCHEME=http
    volumes: 
      - confluenceVolume

  crowd: 
    container_name: crowd_local 
    image: atlassian/crowd:latest 
    environment: 
     - SERVER_PROXY_NAME=crowd.internal
     - SERVER_PROXY_PORT=80
     - SERVER_SCHEME=http
    volumes:
      - crowdVolume 

  nginx: 
    container_name: nginx 
    image: nginx:latest 
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf 
    depends_on: 
     - jira 
     - confluence 
     - crowd 
    ports: 
     - "80:80" 
    networks: 
      default: 
        aliases:
         - jira.internal
         - confluence.internal
         - crowd.internal 